# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ef5167935bd869093f362e1cd9e0a63cb001b0fc75c85ddd09ef8e7dfa71d6e3f2b66a585dea01d1a3c3d36c2359360574f7fc6d1949bd4252a3e09cf334f48

test:
  secret_key_base: 87f099b8bbd4d7bf5094786431e34b108328a3d2bf6f5f929ea2e77ee691c794883fe3534c37cab916b24660493ee8af014988794b3d70aee2882b1f970fb371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
